export const data = [
  {
    id: 1,
    nameA: 'RooiKop Houtkapper',
    nameE: 'Black-collared Barbet',
    images: ['01.png', '02.png', '03.png'],
    audio: 'media1.mov',
  },
  {
    id: 2,
    nameA: 'Kuifkop Houtkapper',
    nameE: 'Crested Barbet',
    images: ['01.png', '02.png', '03.png', '04.png'],
    audio: 'media2.mov',
  },
  {
    id: 3,
    nameA: 'Rooi Bles Tinker',
    nameE: 'Red-fronted Tinkerbird',
    images: ['01.png', '02.png', '03.png', '04.png'],
    audio: 'media3.mov',
  },
  {
    id: 4,
    nameA: 'Bont Houtkapper',
    nameE: 'Acacia Pied Barbet',
    images: ['01.png'],
    audio: 'media4.mov',
  },
  {
    id: 5,
    nameA: 'Bokmakierie',
    nameE: 'Bokmakierie',
    images: ['01.png'],
    audio: 'media5.mov',
  },
  {
    id: 6,
    nameA: 'Suidelike water fiskall',
    nameE: 'Southern Boubou',
    images: ['01.png'],
    audio: 'media6.mov',
  },
  {
    id: 7,
    nameA: 'Konkoit',
    nameE: 'Gorgeous Bushshrike',
    images: ['01.png'],
    audio: 'media7.mov',
  },
  {
    id: 8,
    nameA: 'Olyfboslaksman',
    nameE: 'Olive Bushshrike',
    images: ['01.png'],
    audio: 'media8.mov',
  },
  {
    id: 9,
    nameA: 'Oranjeborslaksman',
    nameE: 'Orange-breasted Bushshrike',
    images: ['01.png'],
    audio: 'media9.mov',
  },
  {
    id: 10,
    nameA: 'Vleiloerie',
    nameE: "Burchekk 's Coucal",
    images: ['01.png'],
    audio: 'media10.mov',
  },
  {
    id: 11,
    nameA: 'Visarend',
    nameE: 'African Fish Eagle',
    images: ['01.png'],
    audio: 'media11.mov',
  },
  {
    id: 12,
    nameA: 'Swartkraai',
    nameE: 'Cape Crow',
    images: ['01.png'],
    audio: 'media12.mov',
  },
  {
    id: 13,
    nameA: 'WitborsKraai',
    nameE: 'Pied Crow',
    images: ['01.png'],
    audio: 'media13.mov',
  },
  {
    id: 14,
    nameA: 'Withalskraai',
    nameE: 'white-necked Raven',
    images: ['01.png'],
    audio: 'media13.mov',
  },
  {
    id: 15,
    nameA: 'Afrikaanse Koekoek',
    nameE: 'African Cuckoo',
    images: ['01.png'],
    audio: 'media13.mov',
  },
]
